name: CD

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        registry-url: 'https://registry.npmjs.org'
    - run: npm ci
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: get-npm-version
     id: package-version
     uses: martinbeentjes/npm-get-version-action@v1
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_NPM_PUBLISH_WEBHOOK }}
        SLACK_TITLE: "New version of eslint-plugin-lendi has been published: ${{steps.package-version.outputs.current-version}}"
    - name: Report Status
      if: always()
      uses: ravsamhq/notify-slack-action@v1
      with:
        status: ${{ job.status }}
        notification_title: 'eslint-plugin-lendi ${{steps.package-version.outputs.current-version}} has failed.'
        notify_when: 'failure'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_NPM_PUBLISH_WEBHOOK }}
